language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t kleinkauff/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kleinkauff/client-test npm run test -- --coverage

after_success:
  - docker build -t kleinkauff/multi-client ./client
  - docker build -t kleinkauff/multi-nginx ./nginx
  - docker build -t kleinkauff/multi-server ./server
  - docker build -t kleinkauff/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kleinkauff/multi-client
  - docker push kleinkauff/multi-nginx
  - docker push kleinkauff/multi-server
  - docker push kleinkauff/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-us-west-2-596254623058
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY